dist: bionic

os: linux

language: ruby

addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - xz-utils
    - zip

jobs:
  include:
  - stage: build
    script: sudo bash ./create-image
  - stage: compress
    script: travis_wait 20 xz -z -k -T0 raspberry-pi-zero-w.img
    script: zip raspberry-pi-zero-w.img.zip raspberry-pi-zero-w.img

deploy:
  provider: releases
  token:
    secure: ycR0+FbWllAb3fox+2/7EHsXufwtNvAs+LOOjxcPtNsfRijDoZrnBUBfdpi4YfHGpoH803sdYBPfAv8+6UqVdxsToRa5CWkOe/6McgSwi9GG3/0fLzOe6Ar11dk0BcWmHOn0MdyChuhtGfOFl45KjWmgH8ySNhPTo9R8ygrVKe9g8eB8QC2y5bYNgGp/ApbHrCIWkVO4lbMNPmCziwWxWOZRCpUk15h05dp/e+yr5cMSYA6YbJ10Zxf14yFwJkIryE1zHd9kbk3tXCAALmZjIuO9Hzk+MU617NOkezigG0qiNzPhY3w19+jmO1C8kRHZBEhOaszSNTDrNlzMF1kkDWnIxj7Pbj1pST8g/y6Z9ZW0GGIU+Bw1QhgpwtlyZpWH1QBwmxOXlQwti3i5as1+iJAcUxi+nFbBZnD8WAzHMInxv0waEb/vrx+SqU9ksx6q0blp7vjl8SHT7nN6GMZBYdtQVUakP+AA/0popnD3c1yo2ERZqyWiIsWj0AiUc92OHlG1/ftg+I73GoO+9KNJsiU5QWgMR8P16QgrcAGAHxvUew1p7EA8qSr6vsZo26UCPj28/SKw2S3LAGieunnv5kruuQsCp2/RmSw4GKZAUlNiUE23VUkTDVOujgyo7vB2bUHutqlPkleyajawma916En90o5veT2+OGa0dWq3dW4=
  file:
  - raspberry-pi-zero-w.img.xz
  - raspberry-pi-zero-w.img.zip
  cleanup: false
  on:
    repo: AutomatedFieldPhenomics/raspberry-pi-zero-w-image
    tags: true
